import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt


t,y1,y2,y3,y,v1,v2,v3,v,E1 = np.genfromtxt('./Data/one1.txt',unpack='True') 

plt.subplot(211)
plt.plot(t,y1,label=r'r1')
plt.plot(t,y2,label=r'r2')
plt.plot(t,y3,label=r'r3')
plt.plot(t,y,label=r'|r|')
plt.ylabel('r(t)')
plt.legend()
plt.subplot(212)
plt.plot(t,v1,label=r'v1')
plt.plot(t,v2,label=r'v2')
plt.plot(t,v3,label=r'v3')
plt.plot(t,v,label=r'|v|')
plt.xlabel('t')
plt.ylabel('v(t)')
plt.legend()
plt.savefig("Plots/plot_A1_1.pdf")
plt.close()

tb,y1,y2,y3,y,v1,v2,v3,v,E1b = np.genfromtxt('./Data/one1b.txt',unpack='True') 
plt.subplot(211)
plt.plot(tb,y1,label=r'r1')
plt.plot(tb,y2,label=r'r2')
plt.plot(tb,y3,label=r'r3')
plt.plot(tb,y,label=r'|r|')
plt.xlabel('t')
plt.ylabel('r(t)')
plt.legend()
plt.subplot(212)
plt.plot(tb,v1,label=r'v1')
plt.plot(tb,v2,label=r'v2')
plt.plot(tb,v3,label=r'v3')
plt.plot(tb,v,label=r'|v|')
plt.xlabel('t')
plt.ylabel('v(t)')
plt.legend()
plt.savefig("Plots/plot_A1_1b.pdf")
plt.close()

tc,y1,y2,y3,y,v1,v2,v3,v,E1c = np.genfromtxt('./Data/one1c.txt',unpack='True') 
plt.subplot(211)
plt.plot(tc,y1,label=r'r1')
plt.plot(tc,y2,label=r'r2')
plt.plot(tc,y3,label=r'r3')
plt.plot(tc,y,label=r'|r|')
plt.ylabel('r(t)')
plt.legend()
plt.subplot(212)
plt.plot(tc,v1,label=r'v1')
plt.plot(tc,v2,label=r'v2')
plt.plot(tc,v3,label=r'v3')
plt.plot(tc,v,label=r'|v|')
plt.xlabel('t')
plt.ylabel('v(t)')
plt.legend()
plt.savefig("Plots/plot_A1_1c.pdf")
plt.close()



t,y1,y2,y3,y,v1,v2,v3,v,E2 = np.genfromtxt('./Data/one2.txt',unpack='True') 
plt.subplot(211)
plt.plot(t,y1,label=r'r1')
plt.plot(t,y2,label=r'r2')
plt.plot(t,y3,label=r'r3')
plt.plot(t,y,label=r'|r|')
plt.ylabel('r(t)')
plt.legend()
plt.subplot(212)
plt.plot(t,v1,label=r'v1')
plt.plot(t,v2,label=r'v2')
plt.plot(t,v3,label=r'v3')
plt.plot(t,v,label=r'|v|')
plt.xlabel('t')
plt.ylabel('v(t)')
plt.legend()
plt.savefig("Plots/plot_A1_2.pdf")
plt.close()



t,y1,y2,y3,y,v1,v2,v3,v,E3 = np.genfromtxt('./Data/one3.txt',unpack='True') 
plt.subplot(211)
plt.plot(t,y1,label=r'r1')
plt.plot(t,y2,label=r'r2')
plt.plot(t,y3,label=r'r3')
plt.plot(t,y,label=r'|r|')
plt.ylabel('r(t)')
plt.legend()
plt.subplot(212)
plt.plot(t,v1,label=r'v1')
plt.plot(t,v2,label=r'v2')
plt.plot(t,v3,label=r'v3')
plt.plot(t,v,label=r'|v|')
plt.xlabel('t')
plt.ylabel('v(t)')
plt.legend()
plt.savefig("Plots/plot_A1_3.pdf")
plt.close()


####    Energie überprüfung
#plt.subplot(311)            ### für selbe r0,v0 und verschiedene h
plt.plot(t,E1,'r-',label=r'E(t) mit h=1/100')
#plt.ylabel('E(t)')
#plt.legend()
#plt.subplot(312)
plt.plot(tb,E1b,'y-',label=r'E(t) mit h=1/10')
#plt.ylabel('E(t)')
#plt.legend()
#plt.subplot(313)
plt.plot(tc,E1c,'g-',label=r'E(t) mit h=1/1000')
plt.xlabel('t')
plt.ylabel('E(t)')
plt.legend()
plt.savefig("Plots/plot_A1_E.pdf")
plt.close()


plt.subplot(311)            ###für unterschiedliche r0,v0 und selbe h
plt.plot(t,E1,'r-',label=r'E1(t)')
plt.ylabel('E(t)')
plt.legend()
plt.subplot(312)
plt.plot(t,E2,color=r'lightcoral',label=r'E2(t)')
plt.ylabel('E(t)')
plt.legend()
plt.subplot(313)
plt.plot(t,E3, color=r'darkred',label=r'E3(t)')
plt.xlabel('t')
plt.ylabel('E(t)')
plt.legend()
plt.savefig("Plots/plot_A1_E2.pdf")
plt.close()



### Abweichung 
h, abw = np.genfromtxt('./Data/one_abw.txt',unpack='True') 
plt.plot(h,abw,label=r'abw(h)')
plt.xlabel('h')
plt.ylabel('abw')
plt.legend()
plt.savefig("Plots/plot_A1_abw.pdf")
plt.close()
