import numpy as np
from numpy import exp
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt
from uncertainties import ufloat
from scipy.stats import sem

t1, x11,x12,x13,v11,v12,v13,E1= np.genfromtxt('./Data/1_1.txt', unpack=True)
t2, x21,x22,x23,v21,v22,v23,E= np.genfromtxt('./Data/1_2.txt', unpack=True)
t3, x31,x32,x33,v31,v32,v33,E= np.genfromtxt('./Data/1_3.txt', unpack=True)
t4, x41,x42,x43,v41,v42,v43,E= np.genfromtxt('./Data/1_4.txt', unpack=True)
h, abw= np.genfromtxt('./Data/1_abw.txt', unpack=True)



plt.figure(1)
plt.plot (t1,x11, 'b-', label='Ort')
plt.plot (t1,v11, 'r-', label='Geschwindigkeit')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_1.pdf')

plt.figure(2)
plt.plot (t1,E1, 'b-', label='Energie')
plt.grid()
plt.xlabel('t')
plt.ylabel('E')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_E.pdf')

plt.figure(3)
plt.plot (t2,x21, 'b-', label='Ort')
plt.plot (t2,v21, 'r-', label='Geschwindigkeit')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_2.pdf')

plt.figure(4)
plt.plot (t3,x31, 'b-', label='Ort')
plt.plot (t3,v31, 'r-', label='Geschwindigkeit')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_3.pdf')

plt.figure(5)
plt.plot (t4,x41, '-', color='darkorchid' ,label='x1')
plt.plot (t4,v41, '-', color='firebrick' ,label='v1')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_4_1.pdf')

plt.figure(6)
plt.plot (t4,x42, '-', color='mediumblue' ,label='x2')
plt.plot (t4,v42, '-', color='tomato' ,label='v2')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_4_2.pdf')

plt.figure(7)
plt.plot (t4,x43, '-', color='lightseagreen' ,label='x3')
plt.plot (t4,v43, '-', color='orange' ,label='v3')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_4_3.pdf')

plt.figure(8)
plt.plot (h,abw, '-', color='firebrick' ,label='abw')
plt.grid()
plt.xlabel('h')
plt.ylabel('abw')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_abw.pdf')

plt.figure(9)
plt.plot (h[3:],abw[3:], '-', color='firebrick' ,label='abw')
plt.grid()
plt.xlabel('h')
plt.ylabel('abw')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_abw_zoom.pdf')
