import numpy as np
from numpy import exp
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt
from uncertainties import ufloat
from scipy.stats import sem

t1, x1,v1, E1= np.genfromtxt('./Data/2_1.txt', unpack=True)
t2, x2,v2, E2= np.genfromtxt('./Data/2_2.txt', unpack=True)
t3, x3,v3, E3= np.genfromtxt('./Data/2_3.txt', unpack=True)
t4, x4,v4, E4= np.genfromtxt('./Data/2_4.txt', unpack=True)
t5, x5,v5, E5= np.genfromtxt('./Data/2_5.txt', unpack=True)
tb, xb,vb, Eb= np.genfromtxt('./Data/2_b.txt', unpack=True)
tc, l_ab, f_ab, l_rk, f_rk= np.genfromtxt('./Data/2_Vergleich.txt', unpack=True)


plt.figure(1)
plt.plot (t1,x1, 'b-', label='Ort')
plt.plot (t1,v1, 'r-', label='Geschwindigkeit')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/2_1.pdf')

plt.figure(2)
plt.plot (t2,x2, 'b-', label='Ort')
plt.plot (t2,v2, 'r-', label='Geschwindigkeit')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/2_2.pdf')

plt.figure(3)
plt.plot (t3,x3, 'b-', label='Ort')
plt.plot (t3,v3, 'r-', label='Geschwindigkeit')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/2_3.pdf')

plt.figure(4)
plt.plot (t4,x4, 'b-', label='Ort')
plt.plot (t4,v4, 'r-', label='Geschwindigkeit')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/2_4.pdf')

plt.figure(5)
plt.plot (t5,x5, 'b-', label='Ort')
plt.plot (t5,v5, 'r-', label='Geschwindigkeit')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/2_5.pdf')

plt.figure(6)
plt.plot (tb,xb, 'b-', label='Ort')
plt.plot (tb,vb, 'r-', label='Geschwindigkeit')
plt.plot (tb,Eb, 'g-', label='Energie/m')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/2_b.pdf')

plt.figure(7)
plt.plot (tc,l_ab, 'rx', label='Adams Bashforth')
plt.plot (tc,l_rk, 'bx', label='Runge Kutta')
plt.grid()
plt.xlabel('t')
plt.xscale('log')
plt.yscale('log')
plt.ylabel('Laufzeit in s')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/2_c_laufzeit.pdf')

plt.figure(8)
plt.plot (tc,f_ab, 'rx', label='Adams Bashforth')
plt.plot (tc,f_rk, 'bx', label='Runge Kutta')
plt.grid()
plt.xlabel('t')
plt.ylabel('Funktionsaufrufe')
plt.xscale('log')
plt.yscale('log')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/2_c_funktionsaufrufe.pdf')
