import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt


t, Sp0, Sp1, T, Epot= np.genfromtxt('./Data/aqu_1.txt', unpack=True)
t_aqu_iso, Sp0_iso, Sp1_iso, T_iso, Epot_iso= np.genfromtxt('./Data/aqu_isokin.txt', unpack=True)

rg1,g1= np.genfromtxt('./Data/g_1.txt', unpack=True)
rg0_01,g0_01= np.genfromtxt('./Data/g_0_01.txt', unpack=True)
rg10,g10= np.genfromtxt('./Data/g_10.txt', unpack=True)
rgiso,giso= np.genfromtxt('./Data/g_isokin.txt', unpack=True)

xstart,ystart= np.genfromtxt('./Data/start.txt', unpack=True)

t_lang1,T1, E1= np.genfromtxt('./Data/T_1.txt', unpack=True)
t_lang0_01,T0_01, E0_01= np.genfromtxt('./Data/T_0_01.txt', unpack=True)
t_lang10,T10, E10= np.genfromtxt('./Data/T_10.txt', unpack=True)
tiso,Tiso, Eiso= np.genfromtxt('./Data/T_isokin.txt', unpack=True)

plt.figure(0)
plt.plot (xstart, ystart,  'ro', label='Teilchen')
plt.grid()
plt.xlim(0,8)
plt.ylim(0,8)
plt.xlabel('y')
plt.ylabel('x')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/start.pdf')


plt.figure(1)
plt.plot (t,T, 'r-', label='$T(t)$')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_T_aqu.pdf')

plt.figure(7)
plt.plot (t_lang1,T1, 'r-', label='$T(t)$')
plt.axhline(y=1.48182, color='k', linestyle='-', label='$< T >$')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_T.pdf')

plt.figure(10)
plt.plot (t_lang0_01,T0_01, 'r-', label='$T(t)$')
plt.axhline(y=0.700231, color='k', linestyle='-', label='$<T >$')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/0_01_T.pdf')

plt.figure(11)
plt.plot (t_lang10,T10, 'r-', label='$T(t)$')
plt.ylim(0,25)
plt.xlim(0,30)
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/10_T.pdf')

plt.figure(8)
plt.plot (tiso,Tiso, 'r-', label='$T(t)$')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_T_iso.pdf')

plt.figure(2)
plt.plot (t,Sp0, 'r-', label='$v_0$')
plt.plot (t,Sp1, 'b-', label='$v_1$')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_SP.pdf')


plt.figure(4)
plt.plot (t[2:],Epot[2:], 'b-', label='Potentielle Energie')
plt.plot (t[2:],15*T[2:], 'r-',label='Kinetische Energie')
plt.plot (t[2:],Epot[2:]+15*T[2:], '-',color='mediumorchid' ,label='Gesamtenergie')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_E.pdf')

plt.figure(16)
plt.plot (t_aqu_iso[2:],Epot_iso[2:], 'b-', label='Potentielle Energie')
plt.plot (t_aqu_iso[2:],15*T_iso[2:], 'r-',label='Kinetische Energie')
plt.plot (t_aqu_iso[2:],Epot_iso[2:]+15*T_iso[2:], '-',color='mediumorchid' ,label='Gesamtenergie')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_E_iso.pdf')

plt.figure(5)
plt.plot (rg1, g1,  'r-', label='g(r)')
plt.grid()
plt.xlabel('r')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_g1.pdf')

plt.figure(13)
plt.plot (rg0_01, g0_01,  'r-', label='g(r)')
plt.grid()
plt.xlabel('r')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_g0_01.pdf')

plt.figure(14)
plt.plot (rg10, g10,  'r-', label='g(r)')
plt.grid()
plt.xlabel('r')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_g10.pdf')



plt.figure(9)
plt.plot (rgiso, giso,  'r-', label='g(r)')
plt.grid()
plt.xlabel('r')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_g_iso.pdf')
