import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

t, Sp0, Sp1, T, Epot= np.genfromtxt('./Data/aqu_1.txt', unpack=True)
rg1,g1= np.genfromtxt('./Data/g_1.txt', unpack=True)
rg0_01,g0_01= np.genfromtxt('./Data/g_0_01.txt', unpack=True)
#rg100,g100= np.genfromtxt('./Data/g_100.txt', unpack=True)
rgiso,giso= np.genfromtxt('./Data/g_isokin_1.txt', unpack=True)
x,y= np.genfromtxt('./Data/end_1.txt', unpack=True)
t2,T2= np.genfromtxt('./Data/T_1.txt', unpack=True)
tiso,Tiso= np.genfromtxt('./Data/T_isokin_1.txt', unpack=True)


plt.figure(1)
plt.plot (t,T, 'r-', label='T')
#plt.ylim(0,4)
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_T_aqu.pdf')

plt.figure(7)
plt.plot (t2,T2, 'r-', label='T')
#plt.ylim(0,4)
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_T.pdf')

plt.figure(8)
plt.plot (tiso,Tiso, 'r-', label='T')
#plt.ylim(0,4)
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_T_iso.pdf')

plt.figure(2)
plt.plot (t,Sp0, 'r-', label='0')
plt.plot (t,Sp1, 'b-', label='1')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_SP.pdf')


plt.figure(4)
plt.plot (t[2:],Epot[2:], 'b-', label='Potentielle Energie')
plt.plot (t[2:],8*T[2:], 'r-',label='Kinetische Energie')
plt.plot (t[2:],Epot[2:]+8*T[2:], '-',color='fuchsia' ,label='Energie')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_E.pdf')

plt.figure(5)
plt.plot (rg1, g1,  'r-', label='G')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_g1.pdf')

plt.figure(10)
plt.plot (rg0_01, g0_01,  'r-', label='G')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_g0_01.pdf')

# plt.figure(11)
# plt.plot (rg100, g100,  'r-', label='G')
# plt.grid()
# plt.xlabel('t')
# plt.ylabel('')
# plt.legend(loc="best")
# plt.tight_layout()
# plt.savefig('Plots/1_g100.pdf')



plt.figure(9)
plt.plot (rgiso, giso,  'r-', label='G')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_g_iso.pdf')

plt.figure(6)
plt.plot (x, y,  'kx', label='G')
plt.grid()
plt.xlabel('t')
plt.ylabel('')
plt.legend(loc="best")
plt.tight_layout()
plt.savefig('Plots/1_end.pdf')
