
all: build/main.pdf

build/main.pdf: FORCE | build
	  TEXINPUTS="$(call translate,build:)" \
	latexmk \
	  --lualatex \
	  --output-directory=build \
	  --interaction=nonstopmode \
	  --halt-on-error \
	main.tex


build:
	mkdir -p build

clean:
	rm -rf build

FORCE:


.PHONY: all clean
